prefix = "#{File.dirname(__FILE__)}"
require "#{prefix}/vehicle_assembly/parser"
require "#{prefix}/vehicle_assembly/task"
require "#{prefix}/vehicle_assembly/configuration"
require "#{prefix}/vehicle_assembly/vehicle"
require "#{prefix}/vehicle_assembly/machinery/load_balancer"
